CREATE DATABASE SMARTCITY;
USE SMARTCITY;

CREATE TABLE TOURISM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(255),
    name VARCHAR(255),
    location VARCHAR(255)
);

CREATE TABLE AcademicInstitutes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(255),
    name VARCHAR(255),
    location VARCHAR(255),
    capacity INT
);

CREATE TABLE NEWS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(1000)
);

CREATE TABLE JOBS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255),
    Description VARCHAR(255)
);

CREATE TABLE JOBS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255),
    Description VARCHAR(255)
);


